version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - mydockernet
    volumes:
      - 'app_mongo:/data/db'
  appserver:
    container_name: appserver
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5005:5005'
    networks:
      - mydockernet
    environment:
      - DEBUG=1
      - NODE_ENV=production
      - TEST=test123
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=mbdb
      - JWT_SECRET=1234567890
    depends_on:
      - mongo
  appclient:
    container_name: appclient
    build:
      context: ./client-pro
      dockerfile: Dockerfile
    networks:
      - mydockernet
    environment:
      - REACT_APP_NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5005
    ports:
      - 8001:8001
    depends_on:
      - appserver
networks:
  mydockernet:
    driver: bridge
volumes:
  app_mongo: null
